kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpserver
  namespace: default
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: sindweller/httpserver2
          env:
            - name: ENV_TYPE
              value: prod
          ports:
            - containerPort: 8840
          resources:
            limits:
              cpu: 2600m
              memory: 4200Mi
            requests:
              cpu: 210m
              memory: 180Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8840
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 15
          startupProbe:
            httpGet:
              path: /
              port: 8840
            failureThreshold: 30
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo Hello Waddles > /usr/share/message"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo exit waddles > /usr/share/message"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: mydockerhub
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 5%
      maxSurge: 5%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600